"""
Freqtrade Strategy Shell — Thin Execution Layer (Multi-Exchange)
================================================================

This is NOT a backtesting strategy. This is an execution shell that:
1. Reads validated parameters from cpcv_params.json (generated by export_params.py)
2. Computes the same signals as our Numba engine (S11 Momentum Burst / S09 Trend)
3. Places trades via Freqtrade's execution engine on ANY supported exchange

The Research Brain (engine.py + CPCV) decides WHAT to trade.
This shell decides HOW to execute it.

Multi-exchange support:
    cpcv_params.json contains per-exchange sections with token availability.
    The strategy auto-detects the exchange from Freqtrade's config and only
    trades tokens listed on that exchange.

Setup:
    1. Run `python export_params.py --strategy s11 --noise 0.003 --exchange kraken,binance`
    2. Copy cpcv_params.json to freqtrade/user_data/strategies/
    3. Copy this file to freqtrade/user_data/strategies/
    4. Use the generated config_<exchange>.json (always starts with dry_run: true)

    freqtrade trade --strategy CpcvSwingStrategy --config config_kraken.json
    freqtrade trade --strategy CpcvSwingStrategy --config config_binance.json
"""

import json
import os
import logging
from datetime import datetime, timedelta
from typing import Optional

import numpy as np
import pandas as pd
import talib.abstract as ta
from freqtrade.strategy import IStrategy, DecimalParameter, IntParameter
from freqtrade.persistence import Trade

logger = logging.getLogger(__name__)


class CpcvSwingStrategy(IStrategy):
    """
    CPCV-Validated Swing Strategy for Freqtrade.

    Reads parameters from cpcv_params.json produced by the research engine.
    Only trades tokens that pass BOTH CPCV and Walk-Forward validation.
    """

    # ── Freqtrade config ──
    timeframe = '1h'
    can_short = False  # spot only for now

    # Loaded from JSON at init, these are defaults
    stoploss = -0.09  # 3x ATR ≈ 9% for typical crypto
    trailing_stop = True
    trailing_stop_positive = 0.015
    trailing_stop_positive_offset = 0.03
    trailing_only_offset_is_reached = True

    # Protection: no stop for first N candles
    use_custom_stoploss = True

    # Position sizing
    stake_amount = 'unlimited'

    # Plotting (optional)
    plot_config = {
        'main_plot': {
            'ema_10': {'color': 'blue'},
            'ema_20': {'color': 'orange'},
            'ema_50': {'color': 'red'},
        },
        'subplots': {
            'ADX': {
                'adx': {'color': 'purple'},
                'plus_di': {'color': 'green'},
                'minus_di': {'color': 'red'},
            },
            'RSI': {
                'rsi': {'color': 'blue'},
            },
        },
    }

    def __init__(self, config: dict) -> None:
        super().__init__(config)

        # Load CPCV parameters from JSON bridge
        params_path = os.path.join(
            config.get('user_data_dir', 'user_data'),
            'strategies', 'cpcv_params.json'
        )

        self.cpcv_params = {}
        self.validated_tokens = []
        self.strategy_type = 's11'  # default
        self.active_exchange = config.get('exchange', {}).get('name', 'unknown')
        self.exchange_info = {}

        if os.path.exists(params_path):
            with open(params_path, 'r') as f:
                self.cpcv_params = json.load(f)

            all_validated = self.cpcv_params.get('validated_tokens', [])
            strat_p = self.cpcv_params.get('strategy_params', {})

            # Filter tokens to those available on the active exchange
            exchanges_data = self.cpcv_params.get('exchanges', {})
            if self.active_exchange in exchanges_data:
                self.exchange_info = exchanges_data[self.active_exchange]
                self.validated_tokens = self.exchange_info.get('tokens', all_validated)
                logger.info(f"Exchange {self.active_exchange}: "
                            f"{len(self.validated_tokens)}/{len(all_validated)} tokens available")
                missing = self.exchange_info.get('missing_tokens', [])
                if missing:
                    logger.warning(f"Tokens not on {self.active_exchange}: {', '.join(missing)}")
            else:
                # Exchange not in params — use all validated tokens (best effort)
                self.validated_tokens = all_validated
                logger.warning(f"Exchange '{self.active_exchange}' not in cpcv_params.json. "
                               f"Using all {len(all_validated)} validated tokens. "
                               f"Available exchanges: {list(exchanges_data.keys())}")

            # Map engine params → Freqtrade params
            stop_mult = strat_p.get('stop_mult', 3.0)
            trail_mult = strat_p.get('trail_mult', 3.0)
            self.no_stop_bars = strat_p.get('no_stop_bars', 24)
            self.min_hold = strat_p.get('min_hold', 18)
            self.max_hold = strat_p.get('max_hold', 720)
            self.edge_estimate = strat_p.get('edge', 0.40)

            # Use exchange-specific fee for slippage awareness
            if self.exchange_info:
                self.exchange_fee = self.exchange_info.get('taker_fee', 0.001)
            else:
                self.exchange_fee = 0.001

            # Detect strategy type from metadata
            strat_name = self.cpcv_params.get('metadata', {}).get('strategy', '')
            if 's09' in strat_name.lower() or 'trend' in strat_name.lower():
                self.strategy_type = 's09'

            logger.info(f"Loaded CPCV params: {len(self.validated_tokens)} tokens on "
                        f"{self.active_exchange}, strategy={self.strategy_type}, "
                        f"no_stop_bars={self.no_stop_bars}")
        else:
            logger.warning(f"cpcv_params.json not found at {params_path}! Using defaults.")

    def informative_pairs(self):
        """We need 4H and daily for multi-timeframe confirmation."""
        pairs = self.dp.current_whitelist()
        informative = []
        for pair in pairs:
            informative.append((pair, '4h'))
            informative.append((pair, '1d'))
        return informative

    def populate_indicators(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        """Compute indicators matching our engine's compute_indicators_fast()."""

        # ── Core indicators ──
        dataframe['ema_10'] = ta.EMA(dataframe, timeperiod=10)
        dataframe['ema_20'] = ta.EMA(dataframe, timeperiod=20)
        dataframe['ema_50'] = ta.EMA(dataframe, timeperiod=50)

        dataframe['rsi'] = ta.RSI(dataframe, timeperiod=14)

        macd = ta.MACD(dataframe, fastperiod=12, slowperiod=26, signalperiod=9)
        dataframe['macd'] = macd['macd']
        dataframe['macd_signal'] = macd['macdsignal']
        dataframe['macd_hist'] = macd['macdhist']

        dataframe['adx'] = ta.ADX(dataframe, timeperiod=14)
        dataframe['plus_di'] = ta.PLUS_DI(dataframe, timeperiod=14)
        dataframe['minus_di'] = ta.MINUS_DI(dataframe, timeperiod=14)

        bb = ta.BBANDS(dataframe, timeperiod=20, nbdevup=2, nbdevdn=2)
        dataframe['bb_upper'] = bb['upperband']
        dataframe['bb_lower'] = bb['lowerband']
        dataframe['bb_mid'] = bb['middleband']

        dataframe['atr'] = ta.ATR(dataframe, timeperiod=14)

        # Volume ratio (current / 20-period average)
        dataframe['vol_sma_20'] = ta.SMA(dataframe['volume'], timeperiod=20)
        dataframe['vol_ratio'] = dataframe['volume'] / dataframe['vol_sma_20'].clip(lower=1)

        # Hourly return
        dataframe['ret_1'] = dataframe['close'].pct_change()

        # Taker buy ratio (if available in data)
        if 'taker_buy_base' in dataframe.columns and 'volume' in dataframe.columns:
            dataframe['taker'] = dataframe['taker_buy_base'] / dataframe['volume'].clip(lower=1)
        else:
            dataframe['taker'] = 0.5  # neutral default

        return dataframe

    def populate_entry_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        """Generate entry signals matching our engine strategies."""

        # Check if this pair's base currency is validated
        pair = metadata['pair']
        base = pair.split('/')[0]
        if base not in self.validated_tokens:
            # Not validated — no trades
            dataframe['enter_long'] = 0
            return dataframe

        if self.strategy_type == 's11':
            dataframe = self._entry_s11(dataframe)
        else:
            dataframe = self._entry_s09(dataframe)

        return dataframe

    def _entry_s11(self, dataframe: pd.DataFrame) -> pd.DataFrame:
        """S11 Momentum Burst: 3% hourly move + ADX > 20 + above EMA20 + volume."""
        dataframe.loc[
            (
                (dataframe['ret_1'] > 0.03) &        # 3% hourly burst
                (dataframe['adx'] > 20) &             # ADX trend filter
                (dataframe['close'] > dataframe['ema_20']) &  # above EMA20
                (dataframe['vol_ratio'] > 1.0) &      # at least avg volume
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1
        return dataframe

    def _entry_s09(self, dataframe: pd.DataFrame) -> pd.DataFrame:
        """S09 Optimized Trend: EMA stack + daily trend + ADX > 30."""
        dataframe.loc[
            (
                (dataframe['close'] > dataframe['ema_10']) &
                (dataframe['ema_10'] > dataframe['ema_20']) &  # EMA stack
                (dataframe['adx'] > 30) &                      # strong trend
                (dataframe['plus_di'] > dataframe['minus_di']) &  # bullish DI
                (dataframe['volume'] > 0)
            ),
            'enter_long'] = 1
        return dataframe

    def populate_exit_trend(self, dataframe: pd.DataFrame, metadata: dict) -> pd.DataFrame:
        """Exit signals — regime change or max hold."""
        # We primarily use custom_stoploss for exits, but add regime-based exits here
        dataframe.loc[
            (
                (dataframe['adx'] < 15) &  # trend has collapsed
                (dataframe['rsi'] > 70)     # overbought in weak trend
            ),
            'exit_long'] = 1
        return dataframe

    def custom_stoploss(self, pair: str, trade: Trade, current_time: datetime,
                        current_rate: float, current_profit: float, **kwargs) -> float:
        """
        Implement the no-stop protection window from our engine.

        For the first `no_stop_bars` hours, return a very wide stoploss (-0.99)
        to prevent early stops. After that, use the trailing stop.
        """
        trade_duration = (current_time - trade.open_date_utc).total_seconds() / 3600

        # Protection window: no stop for first N bars
        if trade_duration < self.no_stop_bars:
            return -0.99  # essentially no stop

        # After protection: use default stoploss (trailing takes over)
        return self.stoploss

    def custom_exit(self, pair: str, trade: Trade, current_time: datetime,
                    current_rate: float, current_profit: float, **kwargs):
        """
        Max hold exit and regime-based exit.
        """
        trade_duration = (current_time - trade.open_date_utc).total_seconds() / 3600

        # Max hold exit
        if trade_duration >= self.max_hold:
            return 'max_hold_exit'

        # Min hold protection
        if trade_duration < self.min_hold:
            return None  # don't exit yet

        return None

    def custom_stake_amount(self, pair: str, current_time: datetime,
                            current_rate: float, proposed_stake: float,
                            min_stake: Optional[float], max_stake: float,
                            leverage: float, entry_tag: Optional[str],
                            side: str, **kwargs) -> float:
        """
        Kelly-based position sizing from our engine.

        Uses tier-based Kelly fraction:
        - Tier 1 (BTC, ETH, SOL, etc.): Half-Kelly
        - Tier 2/3 (smaller alts): Quarter-Kelly
        """
        base = pair.split('/')[0]
        token_stats = self.cpcv_params.get('token_stats', {}).get(base, {})
        tier = token_stats.get('tier', 3)

        # Kelly fraction
        if tier == 1:
            kelly_mult = 0.5
            max_pct = 0.12
        else:
            kelly_mult = 0.25
            max_pct = 0.08 if tier == 2 else 0.04

        # Kelly sizing: f = edge * kelly_mult
        kelly_frac = self.edge_estimate * kelly_mult

        total_balance = self.wallets.get_total('USDT') if hasattr(self, 'wallets') else 200000
        position_size = total_balance * kelly_frac

        # Cap at max percentage
        position_size = min(position_size, total_balance * max_pct)

        # Cap at proposed
        position_size = min(position_size, max_stake)

        return max(position_size, min_stake or 0)

    def confirm_trade_entry(self, pair: str, order_type: str, amount: float,
                            rate: float, time_in_force: str, current_time: datetime,
                            entry_tag: Optional[str], side: str, **kwargs) -> bool:
        """
        Final gate: only allow trades on validated tokens.
        """
        base = pair.split('/')[0]
        if base not in self.validated_tokens:
            logger.info(f"Blocking trade on {pair}: not in validated tokens")
            return False
        return True
